### ISSUE TITLE
RuntimeError: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]

### ISSUE THREAD

**Issue by buithikieu11** [sicxu/Deep3DFaceRecon_pytorch#164]
encountered this error, do you know if it is related to cuda and cudnn that I have installed? Has anyone encountered this error please help me to fix it. Thank you so much.

**Comment by Echo-jyt** [comment]
Have you solved it?

**Comment by Echo-jyt** [comment]
In my case, the error message mentioned that versions after gcc10 are not supported. My gcc version is 12, so I reinstalled gcc10 and set it as the default version. After that, the issue was resolved.
